apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dani-grocery  # Specify your namespace here
spec:
  capacity:
    storage: 1Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce  # Only one node can mount the volume for read/write
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Storage class name (use 'manual' for static provisioning)
  hostPath:
    path: "/mnt/data/mysql"  # Path on the host (only for single-node Kubernetes)
